#pragma config(Motor,  port2,           frontMotor,  tmotorNormal, openLoop)
#pragma config(Motor,  port3,           rightMotor,  tmotorNormal, openLoop)
#pragma config(Motor,  port4,           backMotor,   tmotorNormal, openLoop)
#pragma config(Motor,  port5,           leftMotor,   tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

{
  while(1 == 1)
  {
    /*//left
    motor[frontMotor] = vexRT[Btn8R] * 127;
    motor[backMotor]  = vexRT[Btn8R] * -127;
    //right
    motor[frontMotor] = vexRT[Btn8L] * -127;
    motor[backMotor]  = vexRT[Btn8L] * 127;
    //up
    motor[leftMotor] = vexRT[Btn8U] * 127;
    motor[rightMotor]  = vexRT[Btn8U] * -127;
    //down
    motor[leftMotor] = vexRT[Btn8D] * -127;
    motor[rightMotor]  = vexRT[Btn8D] * 127;*/
    motor[frontMotor] = -vexRT[Ch2];
    motor[backMotor] = vexRT[Ch2];
    motor[leftMotor] = -vexRT[Ch1];
    motor[rightMotor] = vexRT[Ch1];
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
