#pragma config(Sensor, in1,             armAxel,       sensorPotentiometer)
#pragma config(Motor,  port2,           rightDrive,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftDrive,   tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           leftTopArm,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           leftBottomArm,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           rightTopArm,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightBottomArm,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port8,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           frontMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//None of the directions are correct
//There are no comments
//No pushbar control
//---Good luck---


task main(){
	//Do it forever
  while(1 == 1){

  	//Drive control
    motor[leftDrive] = -vexRT[Ch2] / 2;
    motor[rightDrive] = vexRT[Ch3] / 2;


		//Start debugger
		writeDebugStreamLine("%d", SensorValue[armAxel]);

		//Arm Control
		if(vexRT[Btn8U] == 1){
      motor[rightTopArm] = 110;
      motor[rightBottomArm] = 55;
      motor[leftTopArm] = -110;
      motor[leftBottomArm] = -55;
    }
    else if(vexRT[Btn8D] == 1){
      motor[rightTopArm] = -110;
      motor[rightBottomArm] = -55;
      motor[leftTopArm] = 110;
      motor[leftBottomArm] = 55;
    }

    //Claw Control
    else if(vexRT[Btn8L] == 1){
    	motor[clawMotor] = -50;
  	}
  	else if(vexRT[Btn8R] == 1){
    	motor[clawMotor] = 50;
  	}

  	//Pushbar Control
  	else if(vexRT[Btn7U] == 1){
  		motor[frontMotor] = 40;
  	}
  	else if(vexRT[Btn7D] == 1){
  		motor[frontMotor] = -40;
  	}
    else{ //If no puttons are pressed, set motors to 0 turning speed, thus becoming limp.
    	//76 in the start position
    	/*if(SensorValue[armAxel] >= 3137 && SensorValue[armAxel] <= 3800){
				motor[armMotorsL] = -50;
				motor[armMotorsR] = 50;
		  }
			else if(SensorValue[armAxel] <= 4095 && SensorValue[armAxel] > 3800){
				motor[armMotorsL] = 50;
				motor[armMotorsR] = -50;
		  }
		  else{*/
		  motor[rightTopArm] = 0;
      motor[rightBottomArm] = 0;
      motor[leftTopArm] = 0;
      motor[leftBottomArm] = 0;
			//}*/
      motor[frontMotor] = 0;
      motor[clawMotor] = 0;
    }
  }
}
